### ISSUE TITLE
PFCP module modifications to be used for UPF

### ISSUE THREAD

**Issue by ardzoht** [free5gc/pfcp#7]
Hi team,

I'm interested to use this module, to implement N4 interface handling but from UPF, from the historical usages of this module this looks to be used by SMF rather than UPF, but by looking at the code, I don't see references or limitations that this can only be used by SMF. 

My question is, can this be potentially used or modified to be implemented in UPF node side to connect to SMF? 

Thanks

**Comment by andy89923** [comment]
Hi, 

The free5GC's SMF is using this package as a PFCP library. 
You can see it from [here](https://github.com/free5gc/smf/blob/main/go.mod).
